AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PollyAudioBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      BucketName: andrico-polly-audio-files
      Tags:
        - Key: s3
          Value: polly-audio

  AudioInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: songId
          AttributeType: S
        - AttributeName: dateAdded
          AttributeType: S
        - AttributeName: songArtist
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: songId
          KeyType: HASH
        - AttributeName: dateAdded
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: ArtistIndex
          KeySchema:
            - AttributeName: songId
              KeyType: HASH
            - AttributeName: songArtist
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true
      TableName: AudioInfo
      Tags:
        - Key: DynamoDB
          Value: polly-audio
