AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PollyAudioBucket:
    DeletionPolicy: Delete
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      BucketName: andrico-polly-audio-files
      Tags:
      - Key: s3
        Value: polly-audio
    Type: AWS::S3::Bucket
